name: deploy


on:
  push: #test.yml 은 pr 이 올라올 때 시동되었다면, 지금은 push 가 되었을 때 시동된다.
    branches:
     - main #main 브랜치에서만

#github action 에서 사용할 ssh 개인 키를 설정하는 작업
#screts 변수에 저장한 ssh private key 를 ssh_id_rsa 파일에 저장할 것이며 읽기 권한 부여 (서버 접근하려면 개인키 필요)
#known host 도 known host 파일에 저장하고 (해당 서버가 신뢰할 수 있는 서버임을 증명)
#ssh 터널로 들어가서 vm 에 배포하면 된다.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Set up known hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: SSH and deploy #원래는 ssh -i ~/.ssh/github_id_rsa ubuntu@{public ip} 해야했는데, 우린 이미 디폴트 id rsa 를 설정했기 때문에 생략한다.
        run: |
          ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_PUBLIC_IP}} " #이제 SSH 로 들어가서 해당 서버에서 내릴 명령어를 넣으면 된다.
           cd lightstail-cicd-test
           git pull || exit 1
           npm install || exit 1
           npm run build || exit 1
           sudo pkill node || exit 1
           sudo npm run start & npm wait-on http://localhost
           exit
          "